---
- name: Update apt repo and caching
  # become = yes, run as root
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes

- name: Install prerequisite packages
  become: yes
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - conntrack
    state: present
    update_cache: yes

- name: Create apt keyrings directory with specific permissions
  become: yes
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

# Download and add Kubernetes GPG key
- name: Download Kubernetes GPG key
  become: yes
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/Release.key
    dest: /tmp/kubernetes-release.key
    mode: "0644"
    force: yes # always download the file (Checking file)
  register: gpg_key_downloaded

# De-armor GPG key and save to keyrings
- name: De-armor GPG key and save to keyrings
  become: yes
  ansible.builtin.shell:
    cmd: cat /tmp/kubernetes-release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  # if the key was downloaded, run this task
  when: gpg_key_downloaded.changed

- name: Add Kubernetes apt repository
  become: yes
  ansible.builtin.copy:
    # 'dest' the destination that we want to paste file content into it
    dest: /etc/apt/sources.list.d/kubernetes.list
    # 'content' the content that we want to put into the destination file
    content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/deb/ /"
    mode: "0644"

- name: Update apt cache and install Kubernetes tools
  become: yes
  ansible.builtin.apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
    # update_cache: update the apt cache before installing packages (apt-get update)
    update_cache: yes

- name: Prevent Kubernetes packages from being upgraded automatically
  become: yes
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl
