---
- name: Setup Kubernetes Master (Create Cluster)
  hosts: primary_masters
  vars:
    master: "single"
  roles:
    - k8s_master

- name: Setup Kubernetes Workers (Join Cluster)
  hosts: workers
  roles:
    - k8s_worker
